### ISSUE TITLE
4.1.3 doesnt work with my OnePlus5 or S21 Ultra or OnePlus7

### ISSUE THREAD

**Issue by silvershadowkat** [MenosGrante/Rekado#96] opened 2021-04-30 22:54 UTC
I updated to the latest version and payloads no longer send to the switch when i select it. it just does nothing (looks like a black screen crash on the phone after selecting a payload).

It worked perfectly before this update. Has anyone else mentioned any issues since 4.1.3? (i actually thought i bricked my switch or something, but i ended up using tegrarcm on windows to send the payload instead).

**Comment by Evolnotion** [comment] 2021-05-03 02:20
I have a Galaxy 8+ and I have the same problem. Switched to version 4.1.1 and it works.

**Comment by CommandStorm5** [comment] 2021-05-06 12:00
Same problem on Xiaomi Mi 9, latest working version is also 4.1.1

**Comment by mulukou** [comment] 2021-05-08 05:31
Same issue on Galaxy M21s, switching back to 4.1.1 works

**Comment by jayescu** [comment] 2021-05-08 06:29
Same issue on my Pixel 4a, 4.1.1 works.

**Comment by dbw-holic** [comment] 2021-05-15 23:09
Problem reproducible on Huawei Mate 20 Pro and Lenovo Z5s with version 4.1.3
Using older version (<=4.1.1) as a workaround. 
Can confirm it's not the cable as it passes through payload when I inject from my PC and Mac.

**Comment by ir1descent** [comment] 2021-05-16 16:51
Have tried on a Samsung galaxy S8, newer versions don't work, older does.

New version didn't work on an A70 either.

Same issue as others have pointed out. App just does nothing after selecting payload, just goes to a blank screen.

**Comment by Emporioo** [comment] 2021-05-21 18:42
Same problem with the latest versions on S10+. 4.1.1 and lower works ok as has been said.

_Regardless of this, amazing work on this app I use it very often. Thank you !!!_

**Comment by raphamotta** [comment] 2021-06-05 13:47
Same with P30 Pro. Black screen and not injecting payload with the latest version. Using now version 4.1.1 that works fine.

**Comment by MenosGrante** [comment] 2021-07-09 13:18
So, the problem is that I have commented out some important code and it was not finalizing the payload loading process. I have uploaded the 4.1.4 update, please check it and tell me if it is working for you now. If yes, I will close the issue.

https://github.com/MenosGrante/Rekado/releases/tag/4.1.4

**Comment by CommandStorm5** [comment] 2021-07-09 13:24
Fix works for me, Xiaomi MI 9, Thx

**Comment by silvershadowkat** [comment] 2021-07-09 18:24
Fix works for me as one on my oneplus 5. Thank you!

**Closed** 2021-07-09 18:24 UTC
