### ISSUE TITLE
Rekado and TegraExplorer not working

### ISSUE THREAD

**Issue by MultiKoopa** [MenosGrante/Rekado#97] opened 2021-05-03 02:16 UTC
Using Rekado 4.1.3, I cannot send the latest TegraExplorer.bin payload (3.0.4) to my Switch (12.0.1 on SysNAND and EmuMMC, Atmosphere 0.19.2, Hekate 5.5.5, not sure if those last two should really matter in this case).

I can send the payload just fine using TegraRcmGUI.

According to somebody else with a similar issue, downgrading to Rekado 4.1.1 fixes the problem. Any ideas?

**Comment by UntriexTv** [comment] 2021-05-13 12:18
Same for me and my friend (we both use Samsung phones S20fe and brand new a71). We connect mobile to switch with cable from samsung (usb c to usb c) app recognizes switch, but after sending payload app stays on silver (idk if i said right color) screen and switch will not boot up. Only downgrading to 4.1.1 will fork. After selecting payload here it will send and immediately return to payload selection screen as normal.

**Comment by UntriexTv** [comment] 2021-05-13 12:19
Same as #96 !!

**Comment by MenosGrante** [comment] 2021-07-09 13:18
So, the problem is that I have commented out some important code and it was not finalizing the payload loading process. I have uploaded the 4.1.4 update, please check it and tell me if it is working for you now. If yes, I will close the issue.

https://github.com/MenosGrante/Rekado/releases/tag/4.1.4

**Comment by MenosGrante** [comment] 2021-07-10 19:57
The issue was confirmed to be fixed with the 4.1.4 update.

**Closed by MenosGrante** 2021-07-10 19:57 UTC
