### ISSUE TITLE
Payloads are not being pushed from Note 20 Ultra

### ISSUE THREAD

**Issue by thomasGipson** [MenosGrante/Rekado#102] opened 2021-06-06 14:10 UTC
I've tried restarting my phone, using different payloads, updating rekado, checking to make sure my sd cards have the correct files, and all I get when I put my switch into rcm and push a payload is a blank grey screen on my phone. Nothing happens switch-side. It remains in rcm. I am connected to my switch via a usb c to usb c cable
![Screenshot_20210606-100910_Rekado](https://user-images.githubusercontent.com/82129253/120927570-52766780-c6af-11eb-8d45-108b275dd45d.jpg)

**Comment by thomasGipson** [comment] 2021-06-06 14:12
![Screenshot_20210606-101137_Rekado](https://user-images.githubusercontent.com/82129253/120927662-a4b78880-c6af-11eb-9a71-4fb1e0f99ed2.jpg)

**Comment by thomasGipson** [comment] 2021-06-06 14:16
I just tried 4.1.1 and it works flawlessly so something between 4.1.2 and 4.1.3 broke the payload pushing process for me. Let me know if there is anything I can do to help in debugging this issue

**Comment by Crissley10** [comment] 2021-06-09 01:17
I also have this issue. The problem has to be something with the app because I used tegrarcm on PC to boot hekate just fine after having issues with this app.

**Comment by nvitaterna** [comment] 2021-06-19 15:18
Having the same issue here on my S10e. 4.1.1 works fine as well but 4.1.3 does not.

**Comment by ghost9876222** [comment] 2021-06-24 01:35
Same problem with my Samsung a51 it worked with auto injector

**Comment by KonstiDee** [comment] 2021-06-28 19:35
same problem on my Samsung S10+ since the newest update

**Comment by OrGoN3** [comment] 2021-07-01 00:17
Same issue. Setting my desired payload to auto inject works just fine. I'd recommend that for anyone experiencing this issue.

**Comment by ChrisJavier42** [comment] 2021-07-05 23:12
> Same issue. Verizon Google Pixel 3. Android 11. Nothing custom.
> 
> Setting my desired payload to auto inject works just fine. I'd recommend that for anyone experiencing this issue.

This worked for me also! LG G8

**Comment by phonzeh** [comment] 2021-07-09 09:04
Same issue with Huawei P30 Android 11

**Comment by MenosGrante** [comment] 2021-07-09 10:01
I will take a look at this issue today.

**Comment by MenosGrante** [comment] 2021-07-09 13:18
So, the problem is that I have commented out some important code and it was not finalizing the payload loading process. I have uploaded the 4.1.4 update, please check it and tell me if it is working for you now. If yes, I will close the issue.

https://github.com/MenosGrante/Rekado/releases/tag/4.1.4

**Comment by linh1987** [comment] 2021-07-09 16:02
@MenosGrante still doesn't work for me, log says "Sending payload failed at offset 65536"

**Comment by MenosGrante** [comment] 2021-07-10 19:59
@linh1987, your issue is another issue, that is described and discussed in the #9 issue.

The issue was confirmed to be fixed with the 4.1.4 update.

**Closed by MenosGrante** 2021-07-10 19:59 UTC
