### ISSUE TITLE
Not injecting payload on Google Pixel 4a

### ISSUE THREAD

**Issue by Ivaniku** [MenosGrante/Rekado#101] opened 2021-05-28 16:57 UTC
Hi, so I have a Google pixel 4a and rekado used to work perfectly but one day it suddenly stopped working...? 

I don't know if this error is caused by an update but the thing is. From the phone's perspective it seems like the payload has been injected but from the switch's perspective the screen stays black, neither does it leave rcm. I tried using tegrarcmgui to check if the stack had been loaded and it didn't seem like so.

My phone is fully compatible with OTG, here are the logs:

![Screenshot_20210528-185637.png](https://user-images.githubusercontent.com/56933254/120017694-78807580-bfe6-11eb-8681-bab983f0a37e.png)

EDIT: Forgot to mention, thank you for making this amazing software! I really hope this bug can get fixed soon so I can continue using this app. I hope you have a great day!

**Comment by toussii** [comment] 2021-05-31 23:11
Had same issue on my Oneplus 7 Pro for me enabling the auto payload in the options fixed the issue.

**Comment by Ivaniku** [comment] 2021-06-01 17:42
> Had same issue on my Oneplus 7 Pro for me enabling the auto payload in the options fixed the issue.

Sadly, that didn't fix mine

**Comment by Soulspk** [comment] 2021-06-02 20:44
Same problem here, i plug my switch chose the payload i want to inject, all i get is a black screen on my phone and nothing happens on the switch.
Now using 4.1.1 cuz the 4.1.2 crashes.

**Comment by Ivaniku** [comment] 2021-06-10 05:36
> Same problem here with the latest version, i plug my switch chose the payload i want to inject, all i get is a black screen on my phone and nothing happens on the switch.
> Now using 4.1.1 cuz the 4.1.2 crashes.
> 

Huh, same happens to me

**Comment by MenosGrante** [comment] 2021-07-09 13:18
So, the problem is that I have commented out some important code and it was not finalizing the payload loading process. I have uploaded the 4.1.4 update, please check it and tell me if it is working for you now. If yes, I will close the issue.

https://github.com/MenosGrante/Rekado/releases/tag/4.1.4

**Comment by MenosGrante** [comment] 2021-07-10 19:58
The issue was confirmed to be fixed with the 4.1.4 update.

**Closed by MenosGrante** 2021-07-10 19:58 UTC
